services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        container_name: zookeeper_highlight
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.3.0
        container_name: kafka_highlight
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    redis:
        container_name: redis_highlight
        image: redis
        ports:
            - 6381:6379
        volumes:
            - /mnt/data/highlight-data/highlight-data/redis-data:/data
        command:
            - redis-server
            - --save 60 1
            - --loglevel warning

    postgres:
        container_name: postgres
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - /mnt/data/highlight-data/highlight-data/postgres-data:/var/lib/postgresql/data
            - ../scripts/migrations/init.sql:/root/init.sql
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

    clickhouse:
        container_name: clickhouse
        image: clickhouse/clickhouse-server
        ports:
            - 8123:8123
            - 9002:9000
        volumes:
            - /mnt/data/highlight-data/highlight-data/clickhouse-data:/var/lib/clickhouse
            - /mnt/data/highlight-data/highlight-data/clickhouse-logs:/var/log/clickhouse-server

    opensearch:
        container_name: opensearch
        image: opensearchproject/opensearch:1.1.0
        ports:
            - 9202:9200
            - 9600:9600
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: '-Xms128m -Xmx128m'
            DISABLE_INSTALL_DEMO_CONFIG: true
            DISABLE_SECURITY_PLUGIN: true
        volumes:
            - /mnt/data/highlight-data/highlight-data/opensearch-data:/usr/share/opensearch/data
        healthcheck:
            test:
                [
                    'CMD',
                    'curl',
                    '-f',
                    '-u',
                    'admin:admin',
                    'http://localhost:9202',
                ]
            start_period: 180s
            interval: 5s
            timeout: 5s
            retries: 5

    influxdb:
        container_name: influxdb
        image: influxdb:latest
        ports:
            - 8086:8086
        volumes:
            - /mnt/data/highlight-data/highlight-data/influxdb-data:/var/lib/influxdb
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8086/ping']
            start_period: 180s
            interval: 5s
            timeout: 5s
            retries: 5

    collector:
        ports:
            - 4320:4317
            - 4321:4318
        container_name: collector
        image: otel/opentelemetry-collector
        command:
            - '--config=/etc/otel-collector-config.yaml'
        volumes:
            - ./otel-collector.yaml:/etc/otel-collector-config.yaml

# volumes:
#     highlight-data:
#     postgres-data:
#     clickhouse-data:
#     clickhouse-logs:
#     redis-data:
#     opensearch-data:
#     influxdb-data:
